### ISSUE TITLE
Sometimes I run into lost event without "Lost samples" message

### ISSUE THREAD

**Issue by vitalyvch** [iovisor/bcc#1016]
If you have any idea of a possible reason I will be happy to hear. Almost always it is related to SYS_poll and SYS_futex.

Appropriate C code looks in following way:
```C
int main(){
    //...
    syscall(SYS_futex, 1, 2, 3, 4, 5, 6);
    //...
    syscall(SYS_poll, 0x102, 0x103, 0x104, 0x105, 0x106, 0x107);
    //...
}
```

There are no branches, loops, jumps or conditions.

 @brendangregg, @4ast, @goldshtn

**Comment by vitalyvch** [comment]
@marcinslusarz, @GBuella, @ldorau, @plebioda, @sarahjelinek

**Comment by ldorau** [comment]
I have the same problem.

**Comment by vitalyvch** [comment]
More of details:

- the issue could be easily simulated with a trace.py
- almost always we have the problem with a probe on return - handler is just not called.
- rarely we observe missing calls to both handlers. Probably once per one thousand of previous issues.

**Comment by vitalyvch** [comment]
More of details:

- the issue could be easily simulated with a trace.py
- almost always we have the problem with a probe on return - handler is just not called.
- rarely we observe missing calls to both handlers. Probably once per one thousand of previous issues.

**Comment by sarahjelinek** [comment]
It appears this is a more general issue. We originally thought this was something in our code only. However, since we can reproduce it with the trace.py tool it seems as if we are missing calls to handlers. We are relying on the information we get from our utility to determine what system calls an application uses so we can determine what the requirements are for a project. If we have dropped events this calls into question the validity of our data. 

We need some help.

**Comment by ldorau** [comment]
I ran a simple test (I can send you a bash script if someone wants to) and it seems that the bug is in the kernel (as regards futex and poll syscalls).
I added entry and return kprobes for the following syscalls: open, close, write, read, futex, poll 
and in case of futex and poll syscalls many return kprobes were not called:

kprobe_events:
r:kprobes/r_open sys_open
p:kprobes/p_open sys_open
r:kprobes/r_close sys_close
p:kprobes/p_close sys_close
r:kprobes/r_write sys_write
p:kprobes/p_write sys_write
r:kprobes/r_read sys_read
p:kprobes/p_read sys_read
r:kprobes/r_futex sys_futex
p:kprobes/p_futex sys_futex
r:kprobes/r_poll sys_poll
p:kprobes/p_poll sys_poll

Results for the 60-seconds test:
```
open:	p 565	r 565 (0% did not return)
close:	p 633	r 633 (0% did not return)
write:	p 1116	r 1116 (0% did not return)
read:	p 3912	r 3912 (0% did not return)
futex:	p 1698	r 889 (48% did not return)
poll:	p 1819	r 688 (63% did not return)
```

‘p’ – stands for (entry) probe
‘r’ – stands for return probe
like in:
https://www.kernel.org/doc/Documentation/trace/kprobetrace.txt

**Comment by brendangregg** [comment]
@ldorau missing returns is not the same as "lost samples", and we should not conflate these issues. I've seen missing returns from tracers forever, due to compiler optimizations (tail call optimization). If you think there's really bug here (please disassemble and check whether the return points even exist), then it should be a separate bug. And it'd probably get more attention on the perf-users mailing list, as it would be a kprobe bug and not specific to bcc.

OTOH, if you were getting "lost samples" messages somewhere, then it's likely the same bug, se please attach that script.

@vitalyvch see @markdrayton's recent commits with increasing buffer sizes, since you'll want that, and also my polling loop in cpuunclaimed might be interesting to explore (I filed it as #1033). What's the rate of syscalls at which you see lost samples?

**Comment by brendangregg** [comment]
@ldorau I should add: kprobes are not a stable API, and there's no guarantee they'll work at all. Tracing sys_open() might work on one kernel, then break on the next. They are usually ok, but.. The ideal mechanism here is tracepoints.

**Comment by sarahjelinek** [comment]
So, I am confused. eBPF uses kprobes, correct?

**Comment by brendangregg** [comment]
eBPF can attach to kprobes, uprobes, tracepoints, and perf_events.

Many of the existing tools use kprobes when they should use tracepoints, because kprobe/BPF support was added in 4.1, and tracepoint support in 4.7. I'm in no rush to switch them over, since it will break everyone's 4.4 LTS deploys, and, kprobes have been sufficient so far. Probably in a year or two it'll be time for a big kprobe->tracepoint switch.

If you're on post 4.7, you may have better luck with tracepoints. If you're on <4.7, then try to make do with kprobes...

**Comment by brendangregg** [comment]
@vitalyvch question: does your syscall tracer see its own syscalls?

If so, and until you implement the #1033 code, you'll have a feedback loop where the trace is tracing itself tracing itself. At least with #1033 there will be delays inserted. I'd also filter the PID for the tracer in the code, which should fix that particular issue, if you don't already.

**Comment by sarahjelinek** [comment]
We have the problem with this bug:  Can't use syscall tracepoints #748, https://github.com/iovisor/bcc/issues/748. Which means we cannot use tracepoints. We have tried this on the 4.8 and 4.9 kernels and it still does not work.

**Comment by goldshtn** [comment]
I use the raw_syscalls tracepoints in my syscount tool and they work just fine. Why do you need the syscalls (not raw) tracepoints?

**Comment by vitalyvch** [comment]
@brendangregg 

> What's the rate of syscalls at which you see lost samples?

@ldorau has problems with very low rate of syscalls, like few tens per second. But currently, we know that the reason was the issues with kprobes. By the fact we were unable to run into real "Lost samples" after  #997 from a tool in C.

**Comment by ldorau** [comment]
The issue is outdated and it probably does not exist any more.
