### ISSUE TITLE
Run CO-RE version's runqslower failed

### ISSUE THREAD

**Issue by ethercflow** [iovisor/bcc#2770]
I tried to run CO-RE version's runqslower failed, the error info:

> libbpf: sched_wakeup is not found in vmlinux BTF
> libbpf: failed to load object 'runqslower_bpf'
> libbpf: failed to load BPF skeleton 'runqslower_bpf': -2
> failed to load BPF object: -2

My test env is qemu:

``` sh
#!/bin/bash

IMAGE=/data1/env/bpf-next
KERNEL=/data1/kernel/bpf-next

nohup qemu-system-x86_64 \
  -kernel $KERNEL/arch/x86/boot/bzImage \
  -append "console=ttyS0 root=/dev/sda debug earlyprintk=serial slub_debug=QUZ"\
  -hda $IMAGE/stretch.img \
  -fsdev local,security_model=passthrough,id=fsdev0,path=/data2/vmshare \
  -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=hostshare \
  -net user,hostfwd=tcp::10021-:22 -net nic \
  -enable-kvm \
  -nographic \
  -m 2G \
  -smp 2 \
  -pidfile vm.pid \
  2>&1 &
```

I've checked .config about BPF and BTF related:

```
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_ARCH_WANT_DEFAULT_BPF_JIT=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_BPF_JIT_DEFAULT_ON=y
CONFIG_IPV6_SEG6_BPF=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_BPFILTER=y
CONFIG_BPFILTER_UMH=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_LWTUNNEL_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_EVENTS=y
CONFIG_BPF_KPROBE_OVERRIDE=y
CONFIG_TEST_BPF=m
CONFIG_DEBUG_INFO_BTF=y
```

And ` /sys/kernel/btf/vmlinux` exist.

`bin/bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h` is OK.

My host clang version is:

> clang version 10.0.0-++20200115091412+1b264a8263f-1~exp1~20200115082037.1442
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin

Qemu's clang version is:

> clang version 10.0.0-+rc2-1
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin

The tested kernel version is:

> 5.6.0-rc2+ (bpf-next:  commit 8eece07c011f88da0ccf4127fca9a4e4faaf58ae)

BTW, I've submitted a topic in [iovisor-dev@lists.iovisor.org](https://lists.iovisor.org/g/iovisor-dev/topic/run_co_re_version_s/71501560?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,71501560), move to gitHub for better experience.

**Comment by anakryiko** [comment]
Ok, so I missed that you do have BTF built, sorry about that. Let's try to debug further. Can you please provide some more info.

0. Check that you have CONFIG_TRACEPOINTS=y enabled as well (that will disable any tracepoint whatsoever, regardless of BPF).
1. If that doesn't solve your problem,  please provide output of `uname -r`, just to be 100% sure kernel you are running corresponds to what we think is running.
2. Upload full Kconfig (`zcat /proc/config.gz`)
3. Please upload verbose log in runqslower (add -v command line arg) and upload it in full.
4. Please upload full dump of `bin/bpftool btf dump file /sys/kernel/btf/vmlinux` (not a C one)

Once we have that info, we should be able to debug it further.

**Comment by ethercflow** [comment]
> Ok, so I missed that you do have BTF built, sorry about that. Let's try to debug further. Can you please provide some more info.

That's OK. Thank you for your help.

> 
> 0. Check that you have CONFIG_TRACEPOINTS=y enabled as well (that will disable any tracepoint whatsoever, regardless of BPF).

I checked `CONFIG_TRACEPOINTS=y` enabled.

> 1. If that doesn't solve your problem,  please provide output of `uname -r`, just to be 100% sure kernel you are running corresponds to what we think is running.

My host `uname -r`'s output is `5.3.0-28-generic`
My qemu's `uname -r`'s output is `5.6.0-rc2+`
Then I tested `make clean && make` again after make sure I'm in qemu.

> 2. Upload full Kconfig (`zcat /proc/config.gz`)

[config.txt](https://github.com/iovisor/bcc/files/4247473/config.txt)

> 3. Please upload verbose log in runqslower (add -v command line arg) and upload it in full.

[runqslower.log](https://github.com/iovisor/bcc/files/4247482/runqslower.log)

> 4. Please upload full dump of `bin/bpftool btf dump file /sys/kernel/btf/vmlinux` (not a C one)

[vmlinux.txt](https://github.com/iovisor/bcc/files/4247487/vmlinux.txt)

 
> Once we have that info, we should be able to debug it further.

Great!

**Comment by anakryiko** [comment]
@ethercflow, thanks a lot, it's very helpful! Somehow I don't get notifications for BCC repo, so sorry for late reply. Looking at vmlinux.txt, I can confirm that tracepoints are enabled and corresponding generic types are present. But seems like BPF-specific ones (starting with btf_trace_) are not. So let's try to debug it further. Can you also post outputs from:

- `pahole --version`
- `cc --version` (assuming you are using GCC to build kernel?)

It might be weird interactions/behavior of compiler, I'd like to try to repro before I attempt working around it. Thanks!

**Comment by anakryiko** [comment]
@ethercflow, meanwhile, can you also try applying this patch, re-compiling and trying again? https://gist.github.com/anakryiko/002e00b695540d4d5fde2c76ab070f26

If the issue is what I suspect, this should fix it. But please provide pahole and GCC versions anyways.

**Comment by ethercflow** [comment]
> @ethercflow, thanks a lot, it's very helpful! Somehow I don't get notifications for BCC repo, so sorry for late reply. Looking at vmlinux.txt, I can confirm that tracepoints are enabled and corresponding generic types are present. But seems like BPF-specific ones (starting with btf_trace_) are not. So let's try to debug it further. Can you also post outputs from:
> 
> * `pahole --version`
> * `cc --version` (assuming you are using GCC to build kernel?)
> 
> It might be weird interactions/behavior of compiler, I'd like to try to repro before I attempt working around it. Thanks!

> @ethercflow, meanwhile, can you also try applying this patch, re-compiling and trying again? https://gist.github.com/anakryiko/002e00b695540d4d5fde2c76ab070f26
> 
> If the issue is what I suspect, this should fix it. But please provide pahole and GCC versions anyways.

Thank you @anakryiko,  after patch, the `bpf_trace_`  appear in new vmlinux.txt:
[vmlinux_of_patched.txt](https://github.com/iovisor/bcc/files/4253109/vmlinux_of_patched.txt). But the `runqslower`'s bpf prog load still failed. I'll describe the reproduce steps below.

* The `pahole --version` is 1.5
* CC which I used to build kernel is clang, the `cc --version` is:

```
#
# Automatically generated file; DO NOT EDIT.
# Linux/x86 5.6.0-rc2 Kernel Configuration
#

#
# Compiler: clang version 10.0.0-++20200115091412+1b264a8263f-1~exp1~20200115082037.1442
#
CONFIG_GCC_VERSION=0
```

Then I tried to test `runqslower` again, the steps are:
1. Run `git clone https://github.com/iovisor/bcc` to get latest `bcc: commit 08de253fbbc2603d59c19618a3e9f18f5bff7bff`;
2. Run `cd bcc && mkdir build && cd build && cmake ../` to get submodule [libbpf](https://github.com/libbpf/libbpf.git), the commit id is: `583bddce6b93bafa31471212a9811fd7d38b5f9a (HEAD, tag: v0.0.7)`
3. Run `cd bcc/libbpf-tools && rm -rf vmlinux.* && bin/bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h` to get the new `vmlinux.h`;
4. Run `grep "btf_trace_sched" vmlinux.h` to check again `btf_trace_` has already gen:
```c
typedef void (*btf_trace_sched_kthread_stop)(void *, struct task_struct *);
typedef void (*btf_trace_sched_kthread_stop_ret)(void *, int);
typedef void (*btf_trace_sched_wakeup_template)(void *, struct task_struct *);
typedef void (*btf_trace_sched_switch)(void *, bool, struct task_struct *, struct task_struct *);
typedef void (*btf_trace_sched_migrate_task)(void *, struct task_struct *, int);
typedef void (*btf_trace_sched_process_template)(void *, struct task_struct *);
typedef void (*btf_trace_sched_process_wait)(void *, struct pid *);
typedef void (*btf_trace_sched_process_fork)(void *, struct task_struct *, struct task_struct *);
typedef void (*btf_trace_sched_process_exec)(void *, struct task_struct *, pid_t, struct linux_binprm *);
typedef void (*btf_trace_sched_stat_template)(void *, struct task_struct *, u64);
typedef void (*btf_trace_sched_stat_runtime)(void *, struct task_struct *, u64, u64);
typedef void (*btf_trace_sched_pi_setprio)(void *, struct task_struct *, struct task_struct *);
typedef void (*btf_trace_sched_process_hang)(void *, struct task_struct *);
typedef void (*btf_trace_sched_move_task_template)(void *, struct task_struct *, int, int);
typedef void (*btf_trace_sched_swap_numa)(void *, struct task_struct *, int, struct task_struct *, int);
typedef void (*btf_trace_sched_wake_idle_without_ipi)(void *, int);
```
5. Run `make` to build `runqslower`;
6. Run `./runqslower` got error:

> libbpf: tp_btf/sched_wakeup is not found in vmlinux BTF
> libbpf: failed to load object 'runqslower_bpf'
> libbpf: failed to load BPF skeleton 'runqslower_bpf': -2
> failed to load BPF object: -2

It's still failed at `strcmp`:
```c
__s32 btf__find_by_name_kind(const struct btf *btf, const char *type_name,
                             __u32 kind)
{
        __u32 i;

        if (kind == BTF_KIND_UNKN || !strcmp(type_name, "void"))
                return 0;

        for (i = 1; i <= btf->nr_types; i++) {
                const struct btf_type *t = btf->types[i];
                const char *name;

                if (btf_kind(t) != kind)
                        continue;
                name = btf__name_by_offset(btf, t->name_off);
                if (name && !strcmp(type_name, name))
                        return i;
        }

        return -ENOENT;
}
```

From 
```c
SEC("tp_btf/sched_wakeup")
int handle__sched_wakeup(u64 *ctx)
{
	/* TP_PROTO(struct task_struct *p) */
	struct task_struct *p = (void *)ctx[0];

	return trace_enqueue(p->tgid, p->pid);
}

SEC("tp_btf/sched_wakeup_new")
int handle__sched_wakeup_new(u64 *ctx)
{
	/* TP_PROTO(struct task_struct *p) */
	struct task_struct *p = (void *)ctx[0];

	return trace_enqueue(p->tgid, p->pid);
}

SEC("tp_btf/sched_switch")
int handle__sched_switch(u64 *ctx)
{
        ...
}
```
```c
typedef void (*btf_trace_sched_wakeup_template)(void *, struct task_struct *);
typedef void (*btf_trace_sched_switch)(void *, bool, struct task_struct *, struct task_struct *);
```

I guess they correspond? How to make `SEC("tp_btf/sched_wakeup")` `SEC("tp_btf/sched_wakeup_new")` => `btf_trace_sched_wakeup_template` ?
I guess just change `SEC("tp_btf/sched_wakeup")` to `SEC("tp_btf/sched_wakeup_template")` is not the right way.

Due to time, I only tried tried keep
  
```C
SEC("tp_btf/sched_switch")
int handle__sched_switch(u64 *ctx)
{
        ...
}
```
in runqslower.bpf.c, the `runqslower` can work right.

> ➜  libbpf-tools git:(master) ✗ ./runqslower
> Tracing run queue latency higher than 10000 us
> TIME     COMM             TID           LAT(us)
> 03:26:23 runqslower       14824          101322
> 03:26:23 runqslower       14824          101084
> 03:26:23 runqslower       14824          100980

**Comment by anakryiko** [comment]
> > @ethercflow, thanks a lot, it's very helpful! Somehow I don't get notifications for BCC repo, so sorry for late reply. Looking at vmlinux.txt, I can confirm that tracepoints are enabled and corresponding generic types are present. But seems like BPF-specific ones (starting with btf_trace_) are not. So let's try to debug it further. Can you also post outputs from:
> > 
> > * `pahole --version`
> > * `cc --version` (assuming you are using GCC to build kernel?)
> > 
> > It might be weird interactions/behavior of compiler, I'd like to try to repro before I attempt working around it. Thanks!
> 
> > @ethercflow, meanwhile, can you also try applying this patch, re-compiling and trying again? https://gist.github.com/anakryiko/002e00b695540d4d5fde2c76ab070f26
> > If the issue is what I suspect, this should fix it. But please provide pahole and GCC versions anyways.
> 
> Thank you @anakryiko, after patch, the `bpf_trace_` appear in new vmlinux.txt:
> [vmlinux_of_patched.txt](https://github.com/iovisor/bcc/files/4253109/vmlinux_of_patched.txt). But the `runqslower`'s bpf prog load still failed. I'll describe the reproduce steps below.
> 
>     * The `pahole --version` is 1.5

Are you sure it's not 1.15? With 1.5 you wouldn't get BTF at all.

> 
>     * CC which I used to build kernel is clang, the `cc --version` is:
> 
> 
> ```
> #
> # Automatically generated file; DO NOT EDIT.
> # Linux/x86 5.6.0-rc2 Kernel Configuration
> #
> 
> #
> # Compiler: clang version 10.0.0-++20200115091412+1b264a8263f-1~exp1~20200115082037.1442

Ok, so I think that's the reason why those types disappeared, seems like latest Clang doesn't emit type info with current set up. We found the root cause, now we just need to properly fix it.

> 
> 
> ```c
> typedef void (*btf_trace_sched_kthread_stop)(void *, struct task_struct *);
> typedef void (*btf_trace_sched_kthread_stop_ret)(void *, int);
> typedef void (*btf_trace_sched_wakeup_template)(void *, struct task_struct *);

This is the problem with my fix. It now generates types for event **classes**, not for each individual event. I'm trying to come up with the better fix, but we've identified the problem. If you'd like me to add you with Reported-by: tag in kernel patch, can you please give me your full name and email?

> I guess they correspond? How to make `SEC("tp_btf/sched_wakeup")` `SEC("tp_btf/sched_wakeup_new")` => `btf_trace_sched_wakeup_template` ?
> I guess just change `SEC("tp_btf/sched_wakeup")` to `SEC("tp_btf/sched_wakeup_template")` is not the right way.

Yeah, this won't work, unfortunately. We need a proper fix.

**Comment by ethercflow** [comment]
> > > @ethercflow, thanks a lot, it's very helpful! Somehow I don't get notifications for BCC repo, so sorry for late reply. Looking at vmlinux.txt, I can confirm that tracepoints are enabled and corresponding generic types are present. But seems like BPF-specific ones (starting with btf_trace_) are not. So let's try to debug it further. Can you also post outputs from:
> > > 
> > > * `pahole --version`
> > > * `cc --version` (assuming you are using GCC to build kernel?)
> > > 
> > > It might be weird interactions/behavior of compiler, I'd like to try to repro before I attempt working around it. Thanks!
> > 
> > 
> > > @ethercflow, meanwhile, can you also try applying this patch, re-compiling and trying again? https://gist.github.com/anakryiko/002e00b695540d4d5fde2c76ab070f26
> > > If the issue is what I suspect, this should fix it. But please provide pahole and GCC versions anyways.
> > 
> > 
> > Thank you @anakryiko, after patch, the `bpf_trace_` appear in new vmlinux.txt:
> > [vmlinux_of_patched.txt](https://github.com/iovisor/bcc/files/4253109/vmlinux_of_patched.txt). But the `runqslower`'s bpf prog load still failed. I'll describe the reproduce steps below.
> > ```
> > * The `pahole --version` is 1.5
> > ```
> 
> Are you sure it's not 1.15? With 1.5 you wouldn't get BTF at all.
> 

Oh, so sorry. @anakryiko You're right. it's **v1.15**. I should confirm comment carefully before submit.


> > ```
> > * CC which I used to build kernel is clang, the `cc --version` is:
> > ```
> > 
> > 
> > ```
> > #
> > # Automatically generated file; DO NOT EDIT.
> > # Linux/x86 5.6.0-rc2 Kernel Configuration
> > #
> > 
> > #
> > # Compiler: clang version 10.0.0-++20200115091412+1b264a8263f-1~exp1~20200115082037.1442
> > ```
> 
> Ok, so I think that's the reason why those types disappeared, seems like latest Clang doesn't emit type info with current set up. We found the root cause, now we just need to properly fix it.
> 
> > ```c
> > typedef void (*btf_trace_sched_kthread_stop)(void *, struct task_struct *);
> > typedef void (*btf_trace_sched_kthread_stop_ret)(void *, int);
> > typedef void (*btf_trace_sched_wakeup_template)(void *, struct task_struct *);
> > ```
> 
> This is the problem with my fix. It now generates types for event **classes**, not for each individual event. I'm trying to come up with the better fix, but we've identified the problem. If you'd like me to add you with Reported-by: tag in kernel patch, can you please give me your full name and email?
> 
> > I guess they correspond? How to make `SEC("tp_btf/sched_wakeup")` `SEC("tp_btf/sched_wakeup_new")` => `btf_trace_sched_wakeup_template` ?
> > I guess just change `SEC("tp_btf/sched_wakeup")` to `SEC("tp_btf/sched_wakeup_template")` is not the right way.
> 
> Yeah, this won't work, unfortunately. We need a proper fix.

Got it, looking forward, thank you again for your creation, CO-RE is so cool.

**Comment by anakryiko** [comment]
btw, meanwhile to work around that issue, try building kernel with GCC, instead of Clang.

**Comment by ethercflow** [comment]
> btw, meanwhile to work around that issue, try building kernel with GCC, instead of Clang.

Thank you, I've rebuild with `gcc version 8.3.0 (Ubuntu 8.3.0-26ubuntu1~18.04)`,  `runqslower` works very well. I'll try to covert some tools from BCC to libbpf + BPF CO-RE to get more experience.

**Comment by anakryiko** [comment]
Fix in https://patchwork.ozlabs.org/patch/1247243/

**Comment by ethercflow** [comment]
> Fix in https://patchwork.ozlabs.org/patch/1247243/

@anakryiko Thanks a lot, I've tested it `tools/bpf/runqslower` with `Compiler: clang version 10.0.0-++20200115091412+1b264a8263f-1~exp1~20200115082037.1442`. It works as expected.
